### ISSUE TITLE
Adding User Role Permissions if Permissions are not set

### ISSUE THREAD

**Issue by juneX05** [juneX05/bootbox-front#5]
We should add roles permissions to the permissions array just incase the permissions array is empty.

**Comment by SwahnglishCoderz** [comment]
If we do so we are going to face a challenge in how to delete the users permissions...
Unless we only implement it in updating the permissions.

**Comment by juneX05** [comment]
you might have a point. but why do we need to give a user any role then?

**Comment by SwahnglishCoderz** [comment]
We give them a role because permissions are grouped into roles.
Even though we check permissions to keep system consistency but am not sure if we do implement that it will not frustrate admins whenever they want to clear a certain user permissions.

**Comment by juneX05** [comment]
> If we do so we are going to face a challenge in how to delete the users permissions...
> Unless we only implement it in updating the permissions.

Why should an admin clear all users permissions?
I don't think if that can be a clear scenario on how to handle user permissions.

By the way I think we should modify the above idea a bit.
We are going to implement it on both sides but it will only trigger whenever the user has no permissions and the role is changed. Otherwise every control remains to the Admins that they will be able to manage the user permissions the way they want.

**Comment by SwahnglishCoderz** [comment]
Good idea...
Let's see how it will work out.
